// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Services.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Describes the service response property.
    /// </summary>
    public partial class DataTransferServiceResource : ServiceResource
    {
        /// <summary>
        /// Initializes a new instance of the DataTransferServiceResource
        /// class.
        /// </summary>
        public DataTransferServiceResource()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DataTransferServiceResource
        /// class.
        /// </summary>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="creationTime">Time of the last state change (ISO-8601
        /// format).</param>
        /// <param name="instanceSize">Possible values include: 'Cosmos.D4s',
        /// 'Cosmos.D8s', 'Cosmos.D16s'</param>
        /// <param name="instanceCount">Instance count for the service.</param>
        /// <param name="status">Possible values include: 'Creating',
        /// 'Running', 'Updating', 'Deleting', 'Error', 'Stopped'</param>
        /// <param name="locations">An array that contains all of the locations
        /// for the service.</param>
        public DataTransferServiceResource(IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), System.DateTime? creationTime = default(System.DateTime?), string instanceSize = default(string), int? instanceCount = default(int?), string status = default(string), IList<DataTransferRegionalServiceResource> locations = default(IList<DataTransferRegionalServiceResource>))
            : base(additionalProperties, creationTime, instanceSize, instanceCount, status)
        {
            Locations = locations;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets an array that contains all of the locations for the service.
        /// </summary>
        [JsonProperty(PropertyName = "locations")]
        public IList<DataTransferRegionalServiceResource> Locations { get; private set; }

    }
}
