// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Services.Models
{

    /// <summary>
    /// Defines values for ServiceStatus.
    /// </summary>
    public static class ServiceStatus
    {
        public const string Creating = "Creating";
        public const string Running = "Running";
        public const string Updating = "Updating";
        public const string Deleting = "Deleting";
        public const string Error = "Error";
        public const string Stopped = "Stopped";
    }
}
