// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Services.Models
{

    /// <summary>
    /// Defines values for ServiceSize.
    /// </summary>
    public static class ServiceSize
    {
        public const string CosmosD4s = "Cosmos.D4s";
        public const string CosmosD8s = "Cosmos.D8s";
        public const string CosmosD16s = "Cosmos.D16s";
    }
}
