// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Services.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Describes the service response property.
    /// </summary>
    public partial class SqlDedicatedGatewayServiceResource : ServiceResource
    {
        /// <summary>
        /// Initializes a new instance of the
        /// SqlDedicatedGatewayServiceResource class.
        /// </summary>
        public SqlDedicatedGatewayServiceResource()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// SqlDedicatedGatewayServiceResource class.
        /// </summary>
        /// <param name="sqlDedicatedGatewayEndpoint">SqlDedicatedGateway
        /// endpoint for the service.</param>
        /// <param name="additionalProperties">Unmatched properties from the
        /// message are deserialized this collection</param>
        /// <param name="creationTime">Time of the last state change (ISO-8601
        /// format).</param>
        /// <param name="instanceSize">Possible values include: 'Cosmos.D4s',
        /// 'Cosmos.D8s', 'Cosmos.D16s'</param>
        /// <param name="instanceCount">Instance count for the service.</param>
        /// <param name="status">Possible values include: 'Creating',
        /// 'Running', 'Updating', 'Deleting', 'Error', 'Stopped'</param>
        /// <param name="locations">An array that contains all of the locations
        /// for the service.</param>
        public SqlDedicatedGatewayServiceResource(string sqlDedicatedGatewayEndpoint, IDictionary<string, object> additionalProperties = default(IDictionary<string, object>), System.DateTime? creationTime = default(System.DateTime?), string instanceSize = default(string), int? instanceCount = default(int?), string status = default(string), IList<SqlDedicatedGatewayRegionalServiceResource> locations = default(IList<SqlDedicatedGatewayRegionalServiceResource>))
            : base(additionalProperties, creationTime, instanceSize, instanceCount, status)
        {
            SqlDedicatedGatewayEndpoint = sqlDedicatedGatewayEndpoint;
            Locations = locations;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets sqlDedicatedGateway endpoint for the service.
        /// </summary>
        [JsonProperty(PropertyName = "SqlDedicatedGatewayEndpoint")]
        public string SqlDedicatedGatewayEndpoint { get; set; }

        /// <summary>
        /// Gets an array that contains all of the locations for the service.
        /// </summary>
        [JsonProperty(PropertyName = "locations")]
        public IList<SqlDedicatedGatewayRegionalServiceResource> Locations { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (SqlDedicatedGatewayEndpoint == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "SqlDedicatedGatewayEndpoint");
            }
        }
    }
}
